###
# Path
###

export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/bin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/sbin"
export PATH="$PATH:$HOME/.local/bin"

###
# Zsh Customization
###

# Git completions
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash

# Highlight on tab completion selection
zstyle ':completion:*' menu select

###
# Init Zsh
###

# Cache completions aggressively
autoload -Uz compinit
if [ "$(date +'%j')" != "$(stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)" ]; then
    compinit
else
    compinit -C
fi

###
# Theme
###

autoload -U promptinit; promptinit

###
# Dev Scripts sourcing
###

export DEV_SCRIPTS_DIR=~/instinct/dev_scripts
source $DEV_SCRIPTS_DIR/init_dev_scripts.sh
export PATH="$PATH:$DEV_SCRIPTS_DIR/scripts"

###
# Aliases
###

alias ..='cd ..'
alias clear='printf "\033[H\033[2J"'
alias ls='ls -G'
alias la='ls -lAh'
alias gpsup='git push --set-upstream origin HEAD'
alias ggpush='git push origin HEAD'
alias glo='git log --oneline --decorate'
alias glog='git log --oneline --decorate --graph'
alias gst='git status'
alias gstl='git stash list'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gds='git diff --staged'
alias gcm='git checkout master'
alias gf='git fetch'
alias gco='git checkout'
alias ghprvw='gh pr view --web'
alias ghrvw='gh repo view --web'
alias ghieaddme='gh issue edit --add-assignee @me'
alias v='nvim'
alias vd='date +"v%y.%m.%d"'

###
# History
###

# http://zsh.sourceforge.net/Doc/Release/Options.html
SAVEHIST=5000
HISTSIZE=5000
HISTFILE=~/.zsh_history
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt EXTENDED_HISTORY
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

###
# Setting for ctrl-a and ctrl-e
###

bindkey -e

###
# Editor
###

export EDITOR=vi

###
# Zoxide
###

eval "$(zoxide init zsh)"

# 1Password and Docker ssh agent compatibility
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

###
# FZF
###

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# Change the default fzf command to use fd
export FZF_DEFAULT_COMMAND="fd --type f --hidden --no-ignore --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export PRETTIERD_LOCAL_PRETTIER_ONLY=true

eval "$(mise activate zsh)"
eval "$(starship init zsh)"

# Final environment variables
export WS_GITHUB_TOKEN=$(gh auth token)
export ELIXIR_ERL_OPTIONS="-kernel shell_history enabled"
source ~/.config/.env

###
# Highlighting (needs to be last)
###

source /run/current-system/sw/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

