###
# Path
###

export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/bin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/sbin"
export PATH="$PATH:$HOME/.local/bin"

###
# Zsh Customization
###

# Git completions
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash

# Highlight on tab completion selection
zstyle ':completion:*' menu select

###
# Init Zsh
###

autoload -Uz compinit && compinit

###
# Theme
###

autoload -U promptinit; promptinit

###
# Highlighting
###

source /run/current-system/sw/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

###
# Aliases
###

alias ..='cd ..'
alias clear='printf "\033[H\033[2J"'
alias ls='ls -G'
alias la='ls -lAh'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias ggpush='git push origin $(git_current_branch)'
alias glo='git log --oneline --decorate'
alias glog='git log --oneline --decorate --graph'
alias gst='git status'
alias gstl='git stash list'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gds='git diff --staged'
alias gcm='git checkout master'
alias gf='git fetch'
alias gco='git checkout'
alias ghprvw='gh pr view --web'
alias ghrvw='gh repo view --web'
alias ghieaddme='gh issue edit --add-assignee @me'
alias v='nvim'
alias vd='date +"v%y.%m.%d"'
alias llm='op run -- llm'

###
# History
###

# http://zsh.sourceforge.net/Doc/Release/Options.html
SAVEHIST=5000
HISTSIZE=5000
HISTFILE=$HOME/.zsh_history
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt EXTENDED_HISTORY
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

###
# Setting for ctrl-a and ctrl-e
###

bindkey -e

###
# Editor
###

export AIDER_EDITOR=nvim
export EDITOR=vi

###
# Zoxide
###

eval "$(zoxide init zsh)"

###
# FZF
###

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# Change the default fzf command to use ripgrep
export FZF_DEFAULT_COMMAND="rg --hidden --files -g '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export PRETTIERD_LOCAL_PRETTIER_ONLY=true

eval "$(mise activate zsh)"
eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/ohmyposh.toml)"

# Final environment variables
export ANTHROPIC_API_KEY="op://private/llm cli/credential"
