#!/usr/bin/env bash

set -e

export DOTFILES="$PWD"
CONFIG="base"
SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

case $1 in
  work)
    echo "Installing work configuration"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${1}${SUFFIX}" "${@:2}"

    echo "Installing base configuration"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}${SUFFIX}" "${@:2}"
    ;;
  home)
    echo "Installing home configuration"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${1}${SUFFIX}" "${@:2}"

    echo "Installing base configuration"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}${SUFFIX}" "${@:2}"
    ;;
  *)
    echo "Unknown install option ($0), doing nothing"
    ;;
esac
