# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

###
# Path
###

export PATH="/usr/local/mysql/bin"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/bin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/sbin"
export PATH="$PATH:$HOME/.yarn/bin"
export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
export PATH="$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin"
# Homebrew wants this for adding it to the PATH
eval "$(/opt/homebrew/bin/brew shellenv)"

###
# Zsh Customization
###

# Git completions
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash

# Highlight on tab completion selection
zstyle ':completion:*' menu select

###
# Init Zsh
###

fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit

###
# asdf
###

source $HOME/.asdf/asdf.sh

###
# Theme
###

autoload -U promptinit; promptinit

source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme

###
# Aliases
###

# Helper function
# Outputs the name of the current branch
# Usage example: git pull origin $(git_current_branch)
# Using '--quiet' with 'symbolic-ref' will not cause a fatal error (128) if
# it's not a symbolic ref, but in a Git repo.
function git_current_branch() {
  local ref
  ref=$(command git symbolic-ref --quiet HEAD 2> /dev/null)
  local ret=$?
  if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && return  # no git repo.
    ref=$(command git rev-parse --short HEAD 2> /dev/null) || return
  fi
  echo ${ref#refs/heads/}
}

alias ..='cd ..'
alias clear='printf "\033[H\033[2J"'
alias ls='ls -G'
alias la='ls -lAh'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias ggpush='git push origin $(git_current_branch)'
alias glo='git log --oneline --decorate'
alias glog='git log --oneline --decorate --graph'
alias gst='git status'
alias gstl='git stash list'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gds='git diff --staged'
alias gcm='git checkout master'
alias gf='git fetch'
alias gco='git checkout'
alias v='nvim'
alias ctags="`brew --prefix`/bin/ctags"
alias av='aws-vault'
alias vd='date +"v%y.%m.%d"'

###
# History
###

# http://zsh.sourceforge.net/Doc/Release/Options.html
SAVEHIST=5000
HISTSIZE=5000
HISTFILE=~/.zsh_history
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt EXTENDED_HISTORY
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

###
# Setting for ctrl-a and ctrl-e
###

bindkey -e

###
# Editor
###

export EDITOR=vi

# Postgres PGDATA environment variable
export PGDATA=/usr/local/var/postgres

# added by travis gem
[ -f /Users/Troy/.travis/travis.sh ] && source /Users/Troy/.travis/travis.sh

###
# Zoxide
###

eval "$(zoxide init zsh)"

###
# FZF
###

# fzf fuzzy finder awesomeness
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Change the default fzf command to use ripgrep
export FZF_DEFAULT_COMMAND="rg --hidden --files -g '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export PRETTIERD_LOCAL_PRETTIER_ONLY=true

# To customize prompt, run `p10k configure` or edit ~/.dotfiles/zsh/p10k.zsh.
[[ ! -f ~/.dotfiles/zsh/p10k.zsh ]] || source ~/.dotfiles/zsh/p10k.zsh
