#!/bin/sh

if $(command -v mise >/dev/null 2>&1)
then
  echo "› Installing Node with mise"
  mise use --global node@22

  echo "› Installing Python with mise"
  mise use --global python@3.13

  echo "› Installing Elixir (and Erlang) with mise"
  mise use --global erlang elixir@1.18
fi
