#!/bin/sh

if test "$(uname)" = "Darwin"
then
  if ! $(command -v brew >/dev/null 2>&1)
  then
    echo "› Install Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  echo "› brew bundle"
  brew bundle check --file=$DOTFILES/homebrew/Brewfile
  brew bundle --file=$DOTFILES/homebrew/Brewfile
fi
