#!/bin/sh

if ! $(command -v darwin-rebuild >/dev/null 2>&1)
then
  echo "› Install nix-darwin"
  sudo nix run nix-darwin/master#darwin-rebuild -- switch --flake ~/.dotfiles/nix-darwin
else
  echo "› nix-darwin already installed"
fi
