#!/bin/sh
if [ ! -d ~/.asdf ]
then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.4

  # Source the `asdf` script to allow usage of `asdf`
  source ~/.asdf/asdf.sh

  # Node
  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  # Install a version of Node to allow Yarn to work in other scripts
  asdf install nodejs 10.15.0

  # Ruby
  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git

  # Erlang (required for Elixir)
  asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git

  # Elixir
  asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
fi
