#!/bin/sh
if [ ! -d ~/.asdf ]
then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.4

  # Node
  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

  # Ruby
  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
fi
