#!/bin/sh
if [ ! -d ~/.asdf ]
then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.4

  # Source the `asdf` script to allow usage of `asdf`
  echo "› Sourcing ~/.asdf/asdf.sh"
  source ~/.asdf/asdf.sh

  # Node
  echo "› Adding nodejs asdf plugin"
  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  echo "› Adding nodejs keyring"
  bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  # Install a version of Node to allow Yarn to work in other scripts
  echo "› Installing Node with asdf"
  asdf install nodejs 16.13.0
  echo "› Setting default Node version"
  asdf global nodejs 16.13.0

  # Ruby
  echo "› Adding ruby asdf plugin"
  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git

  # Erlang (required for Elixir)
  echo "› Adding erlang asdf plugin"
  asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git

  # Elixir
  echo "› Adding elixir asdf plugin"
  asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git

  # Elm
  echo "› Adding elixir asdf plugin"
  asdf plugin-add elm https://github.com/asdf-community/asdf-elm.git
fi
