#!/bin/sh
#
# Create a Git feature branch.
#
# Prompts user for a Jira issue using the user's Jira CLI configuration and
# creates a feature branch (using the current branch as a base) that conforms
# to our naming conventions.
#
# USAGE:
#   git create-feature-branch
#
# OPTIONS:
#   Optionally set a DEBUG environment variable to enable tracing.
#     $ DEBUG=1 git create-feature-branch
#

# -e: Exit immediately on error
# -u: Treat unset variables as errors
set -eu

# For debugging via an environment variable
case "${DEBUG-}" in
  1 | yes | true) set -x ;;
esac

# Ensure dependencies are installed
. "${DEV_SCRIPTS_DIR}/installers/gum.sh"
. "${DEV_SCRIPTS_DIR}/installers/jira.sh"

if ! ensure_gum; then
  echo "Error: Failed to install required tool 'gum'"
  return 1
fi

if ! ensure_jira; then
  echo "Error: Failed to install required tool 'jira'"
  return 1
fi

if ! command -v jira me >/dev/null 2>&1; then
  echo "Error: Jira CLI is not configured. Run 'jira init'." >&2
  exit 1
fi

# Convert the given string to kebab-case.
#
to_kebab_case() {
  echo "$1" |
    tr '[:upper:]' '[:lower:]' |
    sed 's/[^a-z0-9]/-/g' |
    sed 's/--*/-/g' |
    sed 's/^-//' |
    sed 's/-$//'
}

# Grab all issues ready for dev from Jira and have user select one.
issues=$(jira issue list \
  --jql 'resolution IS EMPTY' \
  --columns key,summary \
  --plain \
  --no-headers)

selected_issue=$(echo "$issues" | gum choose)

# Extract Jira issue key and summary.
key=$(echo "$selected_issue" | awk '{print $1}')
title=$(to_kebab_case "$(echo "$selected_issue" | awk '{$1=""; print $0}' | sed 's/^ *//' | sed 's/\[[^]]*\] *//')")

# Prompt user for branch name.
branch_name=$(gum input --placeholder "Enter branch name" --value "$title")

# Checkout the branch using the `feature/` and Jira issue key prefixes.
git checkout -b "feature/$key-$branch_name"

# TODO: Move the Jira ticket to whatever "in progress" status that the Jira
# board has configured. This can vary by board, so it can't be hard-coded. One
# approach might be to parse the `~/.config/.jira/.config.yml` file to retrieve
# the configured board, then look up the correct status names (maybe from
# another file?).
#
# jira issue move "$key" 'new_status'
