#!/bin/sh

if ! $(command -v prettier >/dev/null 2>&1)
then
  echo "› Installing Prettier with Yarn"
  yarn global add prettier
fi

if ! $(command -v weigh >/dev/null 2>&1)
then
  echo "› Installing Weigh with Yarn"
  yarn global add weigh
fi

if ! $(command -v http-servier >/dev/null 2>&1)
then
  echo "› Installing http-server with Yarn"
  yarn global add http-server
fi
