console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
grey = '#6c6c6c'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:grey'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

    [[blocks.segments]]
      type = 'executiontime'
      style = 'plain'
      background = 'transparent'
      foreground = 'yellow'
      template = '{{ .FormattedMs }}'

      [blocks.segments.properties]
        threshold = 200

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground_templates = [
      '{{ if gt .Code 0 }}red{{ end }}',
      '{{ if eq .Code 0 }}green{{ end }}'
    ]
    template = 'λ'

[transient_prompt]
  background = 'transparent'
  foreground_templates = [
    '{{ if gt .Code 0 }}red{{ end }}',
    '{{ if eq .Code 0 }}green{{ end }}'
  ]
  template = 'λ '

[secondary_prompt]
  background = 'transparent'
  foreground = 'green'
  template = 'λλ '

